language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd .. && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/medicine.zip # AWS CodeDeploy 는 JAR 파일을 인식하지 못한다. -> 압축 파일을 전송한다.

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY             # 외부에서 EC2 에 접근하기 위한 IAM Key
    secret_access_key: $AWS_SECRET_KEY         # 외부에서 EC2 에 접근하기 위한 IAM Key
    bucket: medicine-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy                           # deploy 폴더에 있는 파일들을 s3 버킷에 보낸다.
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: medicine-build                      # AWS S3 Bucket
    key: medicine.zip                           # AWS S3 medicine-build Bucket 에 있는 medicine.zip 파일
    bundle_type: zip
    application: medicine                       # CodeDeploy Application
    deployment_group: medicine-codedeploy-group # CodeDeploy Group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: main

notifications:
  email:
    recipients:
      - pipiolo1024@gmail.com