language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r medicine * # AWS CodeDeploy 는 JAR 파일을 인식하지 못한다. -> 압축 파일을 전송한다.
  - mkdir -p deploy
  - mv medicine.zip deploy/medicine.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: medicine-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy # deploy 폴더에 있는 파일들을 s3 버킷에 보낸다.
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: medicine-build
    key: medicine.zip
    bundle_type: zip
    application: medicine
    deployment_group: medicine-codedeploy-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - pipiolo1024@gmail.com